import React from 'react';
import { Anomaly } from '../types/weather';
import { HelpCircle, X, CheckCircle2, Info, Sparkles } from 'lucide-react';

interface ExplainabilityModalProps {
  isOpen: boolean;
  onClose: () => void;
  anomaly: Anomaly;
}

export const ExplainabilityModal: React.FC<ExplainabilityModalProps> = ({
  isOpen,
  onClose,
  anomaly,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[2000] bg-navy-950/80 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-navy-900 border border-navy-700 rounded-xl max-w-lg w-full p-5 shadow-2xl relative animate-in fade-in zoom-in-95 duration-200">
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-slate-400 hover:text-white p-1 rounded-lg bg-navy-800 hover:bg-navy-700 transition cursor-pointer"
        >
          <X className="w-4 h-4" />
        </button>

        <div className="flex items-center space-x-2 border-b border-navy-700 pb-3">
          <div className="p-2 rounded-lg bg-cyan-500/10 text-cyan-400">
            <HelpCircle className="w-5 h-5" />
          </div>
          <div>
            <h2 className="text-base font-bold text-white">Why was this anomaly detected?</h2>
            <p className="text-xs text-slate-400">Explainable AI Diagnostic Trace ({anomaly.id})</p>
          </div>
        </div>

        <div className="mt-4 space-y-3 text-xs text-slate-300">
          <div className="bg-navy-950 p-3 rounded-lg border border-navy-800">
            <div className="flex items-center justify-between font-bold text-white mb-1">
              <span>Event Classification: {anomaly.event_type}</span>
              <span className="text-rose-400 font-mono">Z-Score: +{anomaly.z_score.toFixed(2)}</span>
            </div>
            <p className="text-slate-400 leading-relaxed">{anomaly.explanation}</p>
          </div>

          <div className="space-y-2">
            <h3 className="font-bold text-slate-200 text-xs uppercase tracking-wider">Key Detection Triggers:</h3>
            
            <div className="flex items-start space-x-2 bg-navy-950/60 p-2.5 rounded border border-navy-800">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold text-white block">Climatological Deviation:</span>
                <span className="text-slate-400">Forecast value ({anomaly.forecast_val_mm} mm) is significantly higher than historical baseline ({anomaly.historical_mean_mm} mm).</span>
              </div>
            </div>

            <div className="flex items-start space-x-2 bg-navy-950/60 p-2.5 rounded border border-navy-800">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold text-white block">Organized Atmospheric Circulation:</span>
                <span className="text-slate-400">Low-level wind vectors and moisture flux convergence indicate sustained severe weather development.</span>
              </div>
            </div>

            <div className="flex items-start space-x-2 bg-navy-950/60 p-2.5 rounded border border-navy-800">
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold text-white block">Temporal Persistence:</span>
                <span className="text-slate-400">Extreme signal persists across at least 5 consecutive ensemble forecast time steps (Days 3 to 7).</span>
              </div>
            </div>
          </div>

          <div className="bg-amber-500/10 border border-amber-500/30 rounded p-2.5 text-[11px] text-amber-300 flex items-center space-x-2">
            <Sparkles className="w-4 h-4 shrink-0 text-amber-400" />
            <span>Note: These diagnostic explanations are generated by the prototype anomaly analysis engine using Z-score baselines.</span>
          </div>
        </div>

        <div className="mt-5 pt-3 border-t border-navy-800 flex justify-end">
          <button
            onClick={onClose}
            className="bg-cyan-500 hover:bg-cyan-400 text-navy-950 font-bold px-4 py-1.5 rounded text-xs transition cursor-pointer"
          >
            Close Explanation
          </button>
        </div>
      </div>
    </div>
  );
};
